---
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint/eslint-plugin'
extends:
  - 'plugin:@typescript-eslint/recommended'
rules:
  'comma-dangle': ['error', 'only-multiline']
  'indent': ['error', 2]
  'quotes': ['error', 'single', { avoidEscape: true }]
  'quote-props': ['error', 'as-needed']
  'semi': ['error', 'always']
  '@typescript-eslint/no-namespace': 'off'
